// Mock Users
export const mockUsers = [
  {
    id: '1',
    name: 'Admin User',
    email: 'admin@inventory.com',
    password: 'admin123',
    role: 'ADMIN',
  },
  {
    id: '2',
    name: 'Staff User',
    email: 'staff@inventory.com',
    password: 'staff123',
    role: 'STAFF',
  },
  {
    id: '3',
    name: 'Viewer User',
    email: 'viewer@inventory.com',
    password: 'viewer123',
    role: 'VIEWER',
  },
]

// Mock Categories
export const mockCategories = [
  {
    id: '1',
    name: 'Electronics',
    description: 'Electronic devices and accessories',
    _count: { items: 5 },
  },
  {
    id: '2',
    name: 'Furniture',
    description: 'Office and home furniture',
    _count: { items: 3 },
  },
  {
    id: '3',
    name: 'Stationery',
    description: 'Office supplies and stationery',
    _count: { items: 4 },
  },
  {
    id: '4',
    name: 'Clothing',
    description: 'Apparel and accessories',
    _count: { items: 0 },
  },
]

// Mock Suppliers
export const mockSuppliers = [
  {
    id: '1',
    name: 'Tech Solutions Inc',
    contactPerson: 'John Smith',
    email: 'john@techsolutions.com',
    phone: '+1-555-0101',
    address: '123 Tech Street, Silicon Valley, CA 94025',
    _count: { items: 5 },
  },
  {
    id: '2',
    name: 'Office Depot',
    contactPerson: 'Sarah Johnson',
    email: 'sarah@officedepot.com',
    phone: '+1-555-0202',
    address: '456 Office Blvd, New York, NY 10001',
    _count: { items: 4 },
  },
  {
    id: '3',
    name: 'Global Furniture Co',
    contactPerson: 'Mike Brown',
    email: 'mike@globalfurniture.com',
    phone: '+1-555-0303',
    address: '789 Furniture Ave, Chicago, IL 60601',
    _count: { items: 3 },
  },
]

// Mock Items
export const mockItems = [
  {
    id: '1',
    sku: 'LAPTOP-001',
    name: 'Laptop Dell XPS 15',
    description: 'High-performance laptop for professionals',
    quantity: 15,
    reorderLevel: 5,
    costPrice: 1200,
    sellPrice: 1500,
    imageUrl: null,
    categoryId: '1',
    supplierId: '1',
    category: { id: '1', name: 'Electronics' },
    supplier: { id: '1', name: 'Tech Solutions Inc' },
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-12-10T15:30:00Z',
  },
  {
    id: '2',
    sku: 'MOUSE-002',
    name: 'Wireless Mouse Logitech MX Master',
    description: 'Ergonomic wireless mouse',
    quantity: 45,
    reorderLevel: 20,
    costPrice: 80,
    sellPrice: 100,
    imageUrl: null,
    categoryId: '1',
    supplierId: '1',
    category: { id: '1', name: 'Electronics' },
    supplier: { id: '1', name: 'Tech Solutions Inc' },
    createdAt: '2024-01-20T09:00:00Z',
    updatedAt: '2024-12-11T14:20:00Z',
  },
  {
    id: '3',
    sku: 'DESK-001',
    name: 'Standing Desk Adjustable',
    description: 'Electric height-adjustable standing desk',
    quantity: 8,
    reorderLevel: 3,
    costPrice: 400,
    sellPrice: 550,
    imageUrl: null,
    categoryId: '2',
    supplierId: '3',
    category: { id: '2', name: 'Furniture' },
    supplier: { id: '3', name: 'Global Furniture Co' },
    createdAt: '2024-02-01T11:00:00Z',
    updatedAt: '2024-12-09T10:15:00Z',
  },
  {
    id: '4',
    sku: 'CHAIR-001',
    name: 'Ergonomic Office Chair',
    description: 'Comfortable chair with lumbar support',
    quantity: 12,
    reorderLevel: 5,
    costPrice: 250,
    sellPrice: 350,
    imageUrl: null,
    categoryId: '2',
    supplierId: '3',
    category: { id: '2', name: 'Furniture' },
    supplier: { id: '3', name: 'Global Furniture Co' },
    createdAt: '2024-02-05T13:00:00Z',
    updatedAt: '2024-12-08T16:45:00Z',
  },
  {
    id: '5',
    sku: 'PEN-001',
    name: 'Ballpoint Pens Black',
    description: 'Pack of 50 black ballpoint pens',
    quantity: 3,
    reorderLevel: 10,
    costPrice: 15,
    sellPrice: 25,
    imageUrl: null,
    categoryId: '3',
    supplierId: '2',
    category: { id: '3', name: 'Stationery' },
    supplier: { id: '2', name: 'Office Depot' },
    createdAt: '2024-03-01T08:00:00Z',
    updatedAt: '2024-12-12T09:30:00Z',
  },
  {
    id: '6',
    sku: 'NOTEBOOK-001',
    name: 'Spiral Notebooks A4',
    description: 'Pack of 10 A4 spiral notebooks',
    quantity: 25,
    reorderLevel: 15,
    costPrice: 20,
    sellPrice: 30,
    imageUrl: null,
    categoryId: '3',
    supplierId: '2',
    category: { id: '3', name: 'Stationery' },
    supplier: { id: '2', name: 'Office Depot' },
    createdAt: '2024-03-10T10:00:00Z',
    updatedAt: '2024-12-11T11:00:00Z',
  },
  {
    id: '7',
    sku: 'MONITOR-001',
    name: '27" 4K Monitor LG UltraFine',
    description: '27-inch 4K UHD IPS monitor',
    quantity: 10,
    reorderLevel: 4,
    costPrice: 500,
    sellPrice: 650,
    imageUrl: null,
    categoryId: '1',
    supplierId: '1',
    category: { id: '1', name: 'Electronics' },
    supplier: { id: '1', name: 'Tech Solutions Inc' },
    createdAt: '2024-03-15T14:00:00Z',
    updatedAt: '2024-12-10T12:00:00Z',
  },
  {
    id: '8',
    sku: 'KEYBOARD-001',
    name: 'Mechanical Keyboard RGB',
    description: 'RGB backlit mechanical keyboard',
    quantity: 18,
    reorderLevel: 10,
    costPrice: 120,
    sellPrice: 180,
    imageUrl: null,
    categoryId: '1',
    supplierId: '1',
    category: { id: '1', name: 'Electronics' },
    supplier: { id: '1', name: 'Tech Solutions Inc' },
    createdAt: '2024-04-01T09:00:00Z',
    updatedAt: '2024-12-09T15:30:00Z',
  },
  {
    id: '9',
    sku: 'LAMP-001',
    name: 'LED Desk Lamp',
    description: 'Adjustable LED desk lamp with USB charging',
    quantity: 4,
    reorderLevel: 8,
    costPrice: 35,
    sellPrice: 50,
    imageUrl: null,
    categoryId: '2',
    supplierId: '3',
    category: { id: '2', name: 'Furniture' },
    supplier: { id: '3', name: 'Global Furniture Co' },
    createdAt: '2024-04-10T11:00:00Z',
    updatedAt: '2024-12-12T10:00:00Z',
  },
  {
    id: '10',
    sku: 'FOLDER-001',
    name: 'File Folders Letter Size',
    description: 'Pack of 100 manila file folders',
    quantity: 35,
    reorderLevel: 20,
    costPrice: 25,
    sellPrice: 40,
    imageUrl: null,
    categoryId: '3',
    supplierId: '2',
    category: { id: '3', name: 'Stationery' },
    supplier: { id: '2', name: 'Office Depot' },
    createdAt: '2024-04-20T13:00:00Z',
    updatedAt: '2024-12-11T14:00:00Z',
  },
  {
    id: '11',
    sku: 'WEBCAM-001',
    name: '1080p HD Webcam',
    description: 'Full HD webcam with microphone',
    quantity: 22,
    reorderLevel: 10,
    costPrice: 60,
    sellPrice: 90,
    imageUrl: null,
    categoryId: '1',
    supplierId: '1',
    category: { id: '1', name: 'Electronics' },
    supplier: { id: '1', name: 'Tech Solutions Inc' },
    createdAt: '2024-05-01T10:00:00Z',
    updatedAt: '2024-12-10T11:00:00Z',
  },
  {
    id: '12',
    sku: 'MARKER-001',
    name: 'Whiteboard Markers Assorted',
    description: 'Pack of 12 dry erase markers',
    quantity: 2,
    reorderLevel: 15,
    costPrice: 10,
    sellPrice: 18,
    imageUrl: null,
    categoryId: '3',
    supplierId: '2',
    category: { id: '3', name: 'Stationery' },
    supplier: { id: '2', name: 'Office Depot' },
    createdAt: '2024-05-10T08:00:00Z',
    updatedAt: '2024-12-13T09:00:00Z',
  },
]

// Mock Transactions
export const mockTransactions = [
  {
    id: '1',
    type: 'IN',
    change: 50,
    reason: 'Initial stock',
    performedBy: 'Admin User',
    itemId: '1',
    item: { name: 'Laptop Dell XPS 15', sku: 'LAPTOP-001' },
    createdAt: '2024-11-01T10:00:00Z',
  },
  {
    id: '2',
    type: 'OUT',
    change: -35,
    reason: 'Sales order #1234',
    performedBy: 'Staff User',
    itemId: '1',
    item: { name: 'Laptop Dell XPS 15', sku: 'LAPTOP-001' },
    createdAt: '2024-11-15T14:30:00Z',
  },
  {
    id: '3',
    type: 'IN',
    change: 100,
    reason: 'Supplier delivery',
    performedBy: 'Admin User',
    itemId: '2',
    item: { name: 'Wireless Mouse Logitech MX Master', sku: 'MOUSE-002' },
    createdAt: '2024-11-20T09:00:00Z',
  },
  {
    id: '4',
    type: 'OUT',
    change: -55,
    reason: 'Bulk order #1245',
    performedBy: 'Staff User',
    itemId: '2',
    item: { name: 'Wireless Mouse Logitech MX Master', sku: 'MOUSE-002' },
    createdAt: '2024-12-01T11:20:00Z',
  },
  {
    id: '5',
    type: 'IN',
    change: 20,
    reason: 'Restock',
    performedBy: 'Admin User',
    itemId: '3',
    item: { name: 'Standing Desk Adjustable', sku: 'DESK-001' },
    createdAt: '2024-12-05T10:00:00Z',
  },
  {
    id: '6',
    type: 'OUT',
    change: -12,
    reason: 'Customer purchase',
    performedBy: 'Staff User',
    itemId: '3',
    item: { name: 'Standing Desk Adjustable', sku: 'DESK-001' },
    createdAt: '2024-12-08T15:45:00Z',
  },
  {
    id: '7',
    type: 'ADJUSTMENT',
    change: -5,
    reason: 'Damaged items',
    performedBy: 'Admin User',
    itemId: '4',
    item: { name: 'Ergonomic Office Chair', sku: 'CHAIR-001' },
    createdAt: '2024-12-09T13:00:00Z',
  },
  {
    id: '8',
    type: 'OUT',
    change: -22,
    reason: 'Sales order #1256',
    performedBy: 'Staff User',
    itemId: '5',
    item: { name: 'Ballpoint Pens Black', sku: 'PEN-001' },
    createdAt: '2024-12-10T10:30:00Z',
  },
  {
    id: '9',
    type: 'IN',
    change: 30,
    reason: 'Supplier delivery',
    performedBy: 'Admin User',
    itemId: '6',
    item: { name: 'Spiral Notebooks A4', sku: 'NOTEBOOK-001' },
    createdAt: '2024-12-11T09:00:00Z',
  },
  {
    id: '10',
    type: 'OUT',
    change: -5,
    reason: 'Customer purchase',
    performedBy: 'Staff User',
    itemId: '6',
    item: { name: 'Spiral Notebooks A4', sku: 'NOTEBOOK-001' },
    createdAt: '2024-12-11T16:20:00Z',
  },
]

// Dashboard Data
export const mockDashboardData = {
  overview: {
    totalItems: 12,
    totalCategories: 4,
    totalSuppliers: 3,
    lowStockCount: 4,
    totalStockValue: '48935.00',
  },
  categoryDistribution: [
    { name: 'Electronics', itemCount: 5, totalQuantity: 110 },
    { name: 'Furniture', itemCount: 3, totalQuantity: 24 },
    { name: 'Stationery', itemCount: 4, totalQuantity: 65 },
  ],
  stockMovement: [
    { date: '2024-12-07', in: 0, out: 0 },
    { date: '2024-12-08', in: 0, out: 12 },
    { date: '2024-12-09', in: 0, out: 5 },
    { date: '2024-12-10', in: 0, out: 22 },
    { date: '2024-12-11', in: 30, out: 5 },
    { date: '2024-12-12', in: 0, out: 0 },
    { date: '2024-12-13', in: 0, out: 0 },
  ],
}

// Low Stock Items
export const mockLowStockItems = mockItems.filter(
  (item) => item.quantity <= item.reorderLevel
)

// Calculate total stock value
export const calculateTotalStockValue = () => {
  return mockItems
    .reduce((total, item) => total + item.quantity * item.costPrice, 0)
    .toFixed(2)
}
